apiVersion: kustomize.config.k8s.io/v1beta1

kind: Kustomization

namespace: todo-production

resources:
  - ../../base
  - namespace.yml

namePrefix: production-

replicas:
  - name: todo-backend
    count: 4
