apiVersion: argoproj.io/v1alpha1

kind: AppProject

metadata:
  name: gitops-demo-project
  namespace: argocd

spec:
  description: Project for GitOps Demo Application

  sourceRepos:
    - https://github.com/dangph12/gitops-demo-manifest

  destinations:
   - namespace: gitops-demo-src
     server: https://kubernetes.default.svc

  clusterResourceWhitelist: []
