apiVersion: argoproj.io/v1alpha1

kind: AppProject

metadata:
  name: gitops-app-project
  namespace: argocd

spec:
  description: Project for GitOps App Application

  sourceRepos:
    - https://github.com/dangph12/gitops-demo

  destinations:
   - namespace: gitops-app
     server: https://kubernetes.default.svc

  clusterResourceWhitelist: []
