apiVersion: argoproj.io/v1alpha1

kind: AppProject

metadata:
  name: todo-project
  namespace: argocd

spec:
  description: Project for Todo Application

  sourceRepos:
    - https://github.com/dangph12/gitops-demo-manifest

  destinations:
   - namespace: todo-app
     server: https://kubernetes.default.svc

  clusterResourceWhitelist: []
