apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-app

spec:
  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: api
          image: nginx
