---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-db-secret
  namespace: todo-app
spec:
  encryptedData:
    password: AgC46axtXdZhWsIieWaOM4TygvMff9TlrZS8yarSV69p99DsffAiAB1JVkKhHA3Jx4xLdjjFkFpgPXAJSQxMLZq5kw90MXKkCattw8/E17B6fLP8IhvIzNuq+EI2HKN0d6C+xuaot7jbbC+u9tX1vxMKZ26QjY/vqEMFe6xbOzSF5r+WRtUU+IfbQ7TYDpIIMe/ehtToXYfp0x9f9RhaXfvXPZLpJyPVnArj7GLT//DNr0fw2XUkxsqby98ILHn+B53gWFQ2EIj/nnJy3sPLSBKXsWlILeCICSVv9Tbu+iyMCsUkbHxxFMeT0MsWVlPwJG4AkT/E6GymFwcQEMupFxBv7+jUY1+vlAAuwPAXVwkpMR2/4GaRrOoL3bVBLKuKXbiQMRUsgRXlAs0O4w2KDXhB3x8uLSCE3+XRW7WiCnv1RjEqLQkTdRtUNxAdiLo3+BcI5UhvmZplMwMMZIill0tkdb0ZF6GRepMMjGxV8eJf3XzrvyJvDCr1ZrzcK3fhBaWvW66g6tEe4zNnBDZbVRfrqTzYIvgXM5fx/KAc9lM8A0Pm6uS0m6yJWcXfLfbqw9AburjwQUS9ekeK2KxNP8qe9fpk3odtJIQv3ttHQD+ww9Gecb784L7ikqE6UvJ2VHOU7ri6UdxA1NjFs3PuvK5xSIL340Co9aMYHL9iD7bF4otK8y9da619KrxRKfactgjsHNwd4C7FY9A=
    username: AgDMXLwspTkTvm4/rrWzeU2Ht5cC2TKLiS7qho2xn9pVKww12Cdb1yUBrT6Vp6VKuxIP2gOlkb8rOreaIc72BCU+31Cv7IyWJBVCP1EsdH3Pxy3soKBuEVmTrdKZuU8Fp17+KIlGHrYFTayJDzjjqIrmjJnKRONmGStmFXrg5pszVnMYFtbFF6OQhwt+AIV8pMbcmaRdysQcXi1Ue+AnriT8/wTFgMYP3DBl5iZekxtOtPeRVbR+Slf46Ypf+uUgMZd2Fsiu0oyURXK4wBlIHW7fJGGVUZRq9G7dr4ieJpOD6HKzsyzIw5SDa1i1WDQmq8VA8E3ffF0lMeZIunZYTyLOnpg0M12l7gFyYFAyR1TfVZFfl2pjIAf9GCkKFOfg/AFS1L7jANAi26KsE14PueRb7Y4X0srBWu6bCzaLupb1R05ABCGmNk23Hx/cnZmilt2zXUYJIErntX4YTO9gshlCjXZ7Cn5LmGRrZtHE3F4IVZya5GR2LxKINmD/cejTUb20tM8q4azS8wKFdwVJ8/4fTV2Urrg7bo7mTajhZXEWqt2bj0RU32fvDxrprO3mLyuVUEzB8fA7idGBaw6LgvNm9M4EqS2eoVCWFskcx/hQnTxDE4GqYSI81k6YU9xWdga2B1dRrnEj+wFywo5DQVgSReOZHJZomUah4QKE2IEWoSDmD/pqp+lkW7tOmg44uDdO68B/
  template:
    metadata:
      name: todo-db-secret
      namespace: todo-app
