apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: helm-app
  namespace: argocd

spec:
  project: helm-project

  source:
    repoURL: https://github.com/dangph12/gitops-demo
    targetRevision: main
    path: apps/helm-app

    helm:
      valueFiles:
        - values/dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: helm-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
