apiVersion: argoproj.io/v1alpha1

kind: Application

metadata:
  name: gitops-demo-src
  namespace: argocd

  annotations:
    argocd-image-updater.argoproj.io/image-list: todo=ghcr.io/dangph12/app-backend

    argocd-image-updater.argoproj.io/todo.update-strategy: digest

    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default

  source:
    repoURL: https://github.com/dangph12/gitops-demo-manifest
    targetRevision: main
    path: apps/gitops-demo-src

  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-demo-src

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
