apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.slack: |
    token: $slack-token

  template.app-sync-succeeded: |
    message: |
      Application {{ .app.metadata.name }} synced successfully

      Revision: {{ .app.status.sync.revision }}
    slack:
      attachments: |
        [{
          "title": "{{ .app.metadata.name }}",
          "text": "Application synced successfully",
          "color": "good"
        }]

  trigger.on-sync-succeeded: |
    - description: Application sync succeeded
      send:
        - app-sync-succeeded
      when: app.status.operationState.phase == 'Succeeded'
